# aws_icon_registry.py

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Optional


class AwsIconRegistry:
    """
    Runtime AWS icon registry.

    Loads:

        aws_icon_catalog.json

    generated by:

        build_icon_registry.py

    Supports:
        - canonical service lookup
        - alias lookup
        - preferred icon selection
        - fuzzy normalization
    """

    def __init__(
        self,
        icon_root: str | Path,
        catalog_path: str | Path,
    ):

        self.icon_root = Path(icon_root)
        self.catalog_path = Path(catalog_path)

        self.preferred: Dict = {}
        self.aliases: Dict[str, str] = {}

        self._load_catalog()

    # ---------------------------------------------------------
    # Catalog Loading
    # ---------------------------------------------------------

    def _load_catalog(self):

        if not self.catalog_path.exists():

            raise FileNotFoundError(
                f"Catalog not found: {self.catalog_path}"
            )

        with open(
            self.catalog_path,
            "r",
            encoding="utf-8",
        ) as f:

            catalog = json.load(f)

        self.preferred = catalog.get(
            "preferred",
            {}
        )

        self._build_alias_index()

    # ---------------------------------------------------------
    # Alias Index
    # ---------------------------------------------------------

    def _build_alias_index(self):

        self.aliases.clear()

        for service, metadata in self.preferred.items():

            canonical = service.lower()

            self.aliases[canonical] = service

            for alias in metadata.get(
                "aliases",
                []
            ):

                self.aliases[
                    alias.lower()
                ] = service

    # ---------------------------------------------------------
    # Normalization
    # ---------------------------------------------------------

    def normalize_service(
        self,
        service: str
    ) -> Optional[str]:

        if not service:
            return None

        key = service.strip().lower()

        return self.aliases.get(key)

    # ---------------------------------------------------------
    # Lookup
    # ---------------------------------------------------------

    def get_icon(
        self,
        service: str
    ) -> Optional[Path]:

        canonical = self.normalize_service(
            service
        )

        if canonical is None:
            return None

        icon = self.preferred.get(
            canonical
        )

        if not icon:
            return None

        return (
            self.icon_root
            / icon["path"]
        )

    def get_metadata(
        self,
        service: str
    ) -> Optional[Dict]:

        canonical = self.normalize_service(
            service
        )

        if canonical is None:
            return None

        return self.preferred.get(
            canonical
        )

    def has_icon(
        self,
        service: str
    ) -> bool:

        return self.get_icon(
            service
        ) is not None

    # ---------------------------------------------------------
    # Enumeration
    # ---------------------------------------------------------

    def services(self):

        return sorted(
            self.preferred.keys()
        )

    def count(self):

        return len(
            self.preferred
        )
